[repository]
name = "hyprzones"
authors = ["Jan Ohlmann (azzuriel)"]
commit_pins = [
    # Pin specific Hyprland versions here
    # ["hyprland-commit-hash", "hyprzones-commit-hash"]
]

[hyprzones]
description = "Zone-based window tiling inspired by FancyZones"
version = "0.3.2"
authors = ["Jan Ohlmann (azzuriel)"]
output = "build/hyprzones.so"
build = [
    "cmake -DCMAKE_BUILD_TYPE=Release -B build",
    "cmake --build build",
    "mkdir -p ~/.config/hyprzones/editor && cp -r editor/* ~/.config/hyprzones/editor/"
]
